In [50]:
%matplotlib tk
import numpy as np
import pandas as pd
import scipy.spatial as sp
import matplotlib as mpl
from matplotlib import pyplot as plt, gridspec as gs
plt.style.use('fivethirtyeight')
from mpl_toolkits.mplot3d import Axes3D

In [6]:
surveys = pd.read_excel('/Volumes/SanDisk/Dsurveys for KDTree.xlsx',header=0)

In [8]:
surveys.describe()
surveys.head()


API_8  API_Extension  Well_ID  TotalDepthMD  TotalDepthTVD  \
0  23720028              0  D-101 I          6805           6383   
1  23720028              0  D-101 I          6805           6383   
2  23720028              0  D-101 I          6805           6383   
3  23720028              0  D-101 I          6805           6383   
4  23720028              0  D-101 I          6805           6383   

   datum_elevation   Datum_name  INCLINATION  AZIMUTH NorthReference  \
0        33.580002  Original KB         0.00     0.00           True   
1        33.580002  Original KB         0.25    69.75           True   
2        33.580002  Original KB         0.00   358.75           True   
3        33.580002  Original KB         0.25   189.75           True   
4        33.580002  Original KB         0.25   239.75           True   

   CONVERGENCE     MD    TVD             X              Y        Lat  \
0     0.096756    0.0    0.0  1.917992e+06  594307.949140  34.346919   
1     0.096756  100.0  100.0  1.917992e+06  594308.010013  34.346919   
2     0.096756  192.0  192.0  1.917992e+06  594308.067858  34.346920   
3     0.096756  286.0  286.0  1.917992e+06  594308.058923  34.346920   
4     0.096756  380.0  380.0  1.917992e+06  594307.992184  34.346919   

         Long  
0 -118.891381  
1 -118.891380  
2 -118.891380  
3 -118.891381  
4 -118.891382

In [62]:
d101 = surveys[(surveys['Well_ID'] == 'D-203') & (surveys['API_Extension'] == 0)][['X','Y','TVD']]
d101.head()
kddata = surveys[(surveys['Well_ID'] != 'D-203')][['X','Y','TVD']]
fig = plt.figure()
ax1 = fig.add_subplot(111,projection='3d')
ax1.scatter(kddata['X'],kddata['Y'],-kddata['TVD'], marker='o',s=0.1)
#ax1.scatter(d101['X'],d101['Y'],-d101['TVD'])
plt.show()

In [54]:

tree = sp.KDTree(kddata)

In [55]:
dist, ind = tree.query(d101, 3)

In [58]:
print(dist,ind)

[[  1.82687639   1.82687639   1.82982076]
 [  2.85059391   3.65815417   3.65815417]
 [  2.8516432    3.56646897   3.56646897]
 [  2.76843649   3.54706144   3.54706144]
 [  2.60496522   3.5378481    3.70904257]
 [  2.52920938   3.9665373    3.9665373 ]
 [  2.70697499   4.15052153   4.15052153]
 [  3.10120215   4.18544829   4.18544829]
 [  3.62011743   4.05603881   4.05603881]
 [  3.8091734    3.84453814   3.84453814]
 [  3.47573227   3.6190883    3.6190883 ]
 [  3.17480144   3.42778296   3.42778296]
 [  3.06004828   3.42772642   3.42772642]
 [  3.20731847   3.68610493   3.68610493]
 [  3.57974751   4.10709806   4.10709806]
 [  4.07809091   4.60675855   4.60675855]
 [  4.59877887   5.12274681   5.12274681]
 [  5.12273898   5.63565141   5.63565141]
 [  5.63653019   6.13998243   6.13998243]
 [  6.13474884   6.63046036   6.63046036]
 [  6.61528424   6.76758832   7.10320974]
 [  6.87776475   7.07622385   7.56358779]
 [  7.0125329    7.55048633   8.04387356]
 [  7.16549389   8.05864223   8.54